version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3308:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
