name: FE CI/CD
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev-fe

env:
    AWS_REGION: ap-northeast-2
    PROFILE_RESOURCE_PATH: ./.env

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./fe

    steps:
      # 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      # node modules 캐싱
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      # .env 파일 생성
      - name: Create .env file
        run: touch './.env'
      - name: Set .env file
        run: echo '${{ secrets.APPLICATION_URL_ENV }}' > './.env'

      # 의존 파일 설치
      - name: Install Dependencies
        run: npm install

      # React Build
      - name: Build
        run: npm run build

      # AWS 접근 권한 부여
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{ env.AWS_REGION }}

      # S3에 배포
      - name: S3 Deploy
        uses: jakejarvis/s3-sync-action@master
        with:
            args: --acl public-read --follow-symlinks --delete
        env:
            AWS_S3_BUCKET: room-number7-presents-react-server
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
            AWS_REGION: ${{ env.AWS_REGION }}
            SOURCE_DIR: './fe/dist'
